# Example:
# python plot_backtraj.py 4km/so2_run/run_so2.pkl

import argparse
import pickle
import numpy as np
from plume_backtraj import (
    plot_parcel_locations,
    plot_parcel_trajectories,
    plot_parcel_age_map,
    plot_parcel_arrival_height_map,
    plot_parcel_emission_time_map,
    plot_missed_parcel_trajectories,
    plot_emission_matrix,
    _format_time_str, # Import the helper function
    compute_height_edges,
)

#python plot_backtraj.py 4km/so2_run/run_so2.pkl --map-extent 30 5 65 30


def parse_args():
    parser = argparse.ArgumentParser(description="Re-plot trajectories from a saved state pickle file.")
    parser.add_argument(
        "pickle_file",
        help="Path to the run_state.pkl file generated by plume_backtraj.py.",
    )
    parser.add_argument(
        "--map-extent",
        nargs=4,
        type=float,
        metavar=("WEST", "SOUTH", "EAST", "NORTH"),
        help="Optional map extent override (west/south/east/north bounds) for all plots.",
    )
    return parser.parse_args()

def main():
    args = parse_args()

    with open(args.pickle_file, "rb") as fh:
        state = pickle.load(fh)

    column = state["column"]["field"]
    xlat = state["grid"]["xlat"]
    xlon = state["grid"]["xlon"]
    script_args = state["args"]
    dpi = script_args["figure_dpi"]
    seed_bbox = tuple(script_args["seed_bbox"]) if script_args.get("seed_bbox") else None
    if args.map_extent is not None:
        map_extent = tuple(args.map_extent)
    else:
        map_extent = script_args.get("map_extent")
        if map_extent is not None:
            map_extent = tuple(map_extent)

    # Approximate initial-height array from trajectories (first k level)
    n_parcels = state["trajectories"]["i"].shape[1]
    init_heights = state["trajectories"].get("initial_height_m")
    if init_heights is None:
        init_heights = (
            state.get("initial_parcels", {}).get("z_init")
            if state.get("initial_parcels")
            else None
        )
    if init_heights is not None:
        init_heights = np.asarray(init_heights)
    if init_heights is None or init_heights.shape[0] != n_parcels:
        init_heights = None

    plot_parcel_trajectories(
        column2d=column,
        xlat=xlat,
        xlon=xlon,
        trajectory_times=state["trajectories"]["times"],
        trajectory_i=state["trajectories"]["i"],
        trajectory_j=state["trajectories"]["j"],
        trajectory_active=state["trajectories"]["active"],
        arrived_flags=state["trajectories"]["arrived_mask"],
        threshold=script_args["threshold"],
        receptor_lat=script_args["receptor_lat"],
        receptor_lon=script_args["receptor_lon"],
        receptor_radius_m=script_args["receptor_radius"],
        seed_bbox=seed_bbox,
        out_path="trajectories_replot.png",
        colorbar_label=state["column"]["colorbar_label"],
        initial_heights=init_heights,
        z_min=script_args.get("z_min"),
        z_max=script_args.get("z_max"),
        figure_dpi=dpi,
        map_extent=map_extent,
    )

    # Initial parcels may not be saved; skip the seed map unless we stored them
    if "initial_parcels" in state and state["initial_parcels"]:
        plot_parcel_locations(
            column2d=column,
            xlat=xlat,
            xlon=xlon,
            parcels=state["initial_parcels"],
            out_path="parcel_locations_replot.png",
            threshold=script_args["threshold"],
            receptor_lat=script_args["receptor_lat"],
            receptor_lon=script_args["receptor_lon"],
            receptor_radius_m=script_args["receptor_radius"],
            seed_bbox=seed_bbox,
            colorbar_label=state["column"]["colorbar_label"],
            title=(
                "Parcel seeds at "
                f"{_format_time_str(state['metadata'].get('start_time', ''))}\n"
                f"(WRF index {state['metadata']['start_time_index']})"
            ),
            figure_dpi=dpi,
            map_extent=map_extent,
        )

    plot_parcel_age_map(
        column2d=column,
        xlat=xlat,
        xlon=xlon,
        trajectory_i=state["trajectories"]["i"],
        trajectory_j=state["trajectories"]["j"],
        trajectory_active=state["trajectories"]["active"],
        parcel_indices=state["trajectories"]["indices_in_bins"],
        parcel_ages_hours=state["trajectories"]["arrival_age_hours"],
        threshold=script_args["threshold"],
        receptor_lat=script_args["receptor_lat"],
        receptor_lon=script_args["receptor_lon"],
        receptor_radius_m=script_args["receptor_radius"],
        out_path="trajectory_ages_replot.png",
        colorbar_label=state["column"]["colorbar_label"],
        figure_dpi=dpi,
        seed_bbox=seed_bbox,
        map_extent=map_extent,
    )

    emission_time_hours = state["trajectories"].get("emission_time_hours")
    emission_start_time = state.get("metadata", {}).get("emission_start")
    if emission_start_time is None:
        emission_start_time = np.datetime64("2025-11-23T08:30:00")

    if emission_time_hours is None:
        arrival_age_hours = state["trajectories"].get("arrival_age_hours")
        start_time = state.get("metadata", {}).get("start_time")
        
        if start_time is not None:
            start_time = np.datetime64(start_time)

        if arrival_age_hours is not None and start_time is not None:
            start_time_sec = (
                (start_time - emission_start_time) / np.timedelta64(1, "s")
            ).astype(float)
            emission_time_hours = start_time_sec / 3600.0 - np.asarray(arrival_age_hours, dtype=float)
            print("[diag] Derived emission-time data from arrival ages using default emission start 2025-11-23 08:30 UTC.")
        else:
            print("[diag] No emission-time data in pickle and cannot derive it; skipping emission-time plot.")
    if emission_time_hours is not None:
        plot_parcel_emission_time_map(
            column2d=column,
            xlat=xlat,
            xlon=xlon,
            trajectory_i=state["trajectories"]["i"],
            trajectory_j=state["trajectories"]["j"],
            trajectory_active=state["trajectories"]["active"],
            parcel_indices=state["trajectories"]["indices_in_bins"],
            parcel_emission_time_hours=emission_time_hours,
            threshold=script_args["threshold"],
            receptor_lat=script_args["receptor_lat"],
            receptor_lon=script_args["receptor_lon"],
            receptor_radius_m=script_args["receptor_radius"],
            out_path="trajectory_emission_time_replot.png",
            colorbar_label=state["column"]["colorbar_label"],
            figure_dpi=dpi,
            emission_start_time=emission_start_time,
            seed_bbox=seed_bbox,
            map_extent=map_extent,
        )
    else:
        print("[diag] No emission-time plot generated.")

    plot_parcel_arrival_height_map(
        column2d=column,
        xlat=xlat,
        xlon=xlon,
        trajectory_i=state["trajectories"]["i"],
        trajectory_j=state["trajectories"]["j"],
        trajectory_active=state["trajectories"]["active"],
        parcel_indices=state["trajectories"]["indices_in_bins"],
        parcel_arrival_height_m=state["trajectories"]["arrival_height_m"],
        threshold=script_args["threshold"],
        receptor_lat=script_args["receptor_lat"],
        receptor_lon=script_args["receptor_lon"],
        receptor_radius_m=script_args["receptor_radius"],
        out_path="trajectory_arrival_height_replot.png",
        colorbar_label=state["column"]["colorbar_label"],
        figure_dpi=dpi,
        height_min=script_args.get("z_min"),
        height_max=script_args.get("z_max"),
        seed_bbox=seed_bbox,
        map_extent=map_extent,
    )

    missed_indices = np.where(~state["trajectories"]["arrived_mask"])[0]
    if missed_indices.size:
        plot_missed_parcel_trajectories(
            column2d=column,
            xlat=xlat,
            xlon=xlon,
            trajectory_i=state["trajectories"]["i"],
            trajectory_j=state["trajectories"]["j"],
            trajectory_active=state["trajectories"]["active"],
            arrived_flags=state["trajectories"]["arrived_mask"],
            initial_heights=init_heights,
            final_heights=state["trajectories"]["final_z"],
            threshold=script_args["threshold"],
            receptor_lat=script_args["receptor_lat"],
            receptor_lon=script_args["receptor_lon"],
            receptor_radius_m=script_args["receptor_radius"],
            out_path="missed_trajectories_replot.png",
            z_min=script_args.get("z_min"),
            z_max=script_args.get("z_max"),
            figure_dpi=dpi,
            seed_bbox=seed_bbox,
            map_extent=map_extent,
        )

    plot_emission_matrix(
        emission=state["emission"]["matrix"],
        time_edges=state["emission"]["time_edges"],
        z_bins=state["emission"]["z_bins"],
        z_edges=state["emission"]["z_edges"],
        time_labels=state["emission"]["time_labels"],
        out_path="emission_matrix_replot.png",
        time_axis_mode=state["emission"]["time_axis_mode"],
        total_parcels=state["emission"]["total_parcels"],
        figure_dpi=dpi,
    )
    
    # Save the emission matrix to a text file
    emission_matrix = state["emission"]["matrix"]
    time_labels = state["emission"]["time_labels"]
    z_bins = state["emission"]["z_bins"]
    nz_bins = z_bins.size
    n_time_bins = len(time_labels)
    
    with open("emission_matrix_replot.txt", "w") as f:
        f.write("time " + " ".join(time_labels) + "\n")
        f.write("height " + " ".join(f"{z:.2f}" for z in z_bins) + "\n")
        for iz in range(nz_bins - 1, -1, -1):
            row_vals = " ".join(f"{int(round(emission_matrix[iz, jt]))}" for jt in range(n_time_bins))
            f.write(row_vals + "\n")
    print("Time–height emission series written to 'emission_matrix_replot.txt'.")

    # Plot the mass-weighted emission matrix if it exists
    if "mass_matrix" in state["emission"] and state["emission"]["mass_matrix"] is not None:
        print("[diag] Re-plotting mass-weighted emission matrix.")
        plot_emission_matrix(
            emission=state["emission"]["mass_matrix"],
            time_edges=state["emission"]["time_edges"],
            z_bins=state["emission"]["z_bins"],
            z_edges=state["emission"]["z_edges"],
            time_labels=state["emission"]["time_labels"],
            out_path="mass_matrix_replot.png",
            time_axis_mode=state["emission"]["time_axis_mode"],
            total_parcels=None, # Mass plot doesn't show parcel count
            colorbar_label="Parcel mass",
            figure_dpi=dpi,
        )
        
        # Save the mass-weighted emission matrix to a text file
        mass_matrix = state["emission"]["mass_matrix"]
        with open("mass_matrix_replot.txt", "w") as f:
            f.write("time " + " ".join(time_labels) + "\n")
            f.write("height " + " ".join(f"{z:.2f}" for z in z_bins) + "\n")
            for iz in range(nz_bins - 1, -1, -1):
                row_vals = " ".join(
                    f"{mass_matrix[iz, jt]:.6e}" for jt in range(n_time_bins)
                )
                f.write(row_vals + "\n")
        print("Mass-weighted emission series written to 'mass_matrix_replot.txt'.")



if __name__ == "__main__":
    main()
