import argparse
import pickle
import numpy as np

'''
python plot_forwtraj.py forward_run.pkl \
  --height-figure my_height.png \
  --age-figure my_age.png \
  --seeds-vertical-figure seeds_vertical.png

'''

from plume_forwtraj import (
    plot_trajectories_by_height,
    plot_trajectories_by_age,
    plot_seed_vertical_distribution,
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Re-plot forward trajectories from a saved state pickle file."
    )
    parser.add_argument(
        "pickle_file",
        help="Path to the pickle file generated by plume_forwtraj.py.",
    )
    parser.add_argument(
        "--height-figure",
        default="plume_height_colored_replot.png",
        help="Output PNG for trajectories colored by height.",
    )
    parser.add_argument(
        "--age-figure",
        default="plume_age_colored_replot.png",
        help="Output PNG for trajectories colored by age.",
    )
    parser.add_argument(
        "--seeds-vertical-figure",
        default=None,
        help="Optional PNG for the initial vertical distribution of parcels.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    with open(args.pickle_file, "rb") as fh:
        state = pickle.load(fh)

    grid = state["grid"]
    trajectories = state["trajectories"]
    script_args = state.get("args", {})

    xlat = np.asarray(grid["xlat"])
    xlon = np.asarray(grid["xlon"])

    height_hist = trajectories.get("height_hist_m")
    if height_hist is None:
        raise ValueError("Pickle does not contain height history.")

    seed_bbox = script_args.get("seed_bbox")
    if seed_bbox is not None:
        seed_bbox = tuple(seed_bbox)

    fig_dpi = int(script_args.get("figure_dpi", 200))
    z_min = script_args.get("z_min")
    z_max = script_args.get("z_max")
    source_lat = script_args.get("source_lat")
    source_lon = script_args.get("source_lon")

    plot_trajectories_by_height(
        xlat=xlat,
        xlon=xlon,
        trajectory_i=trajectories["i"],
        trajectory_j=trajectories["j"],
        trajectory_active=trajectories["active"],
        height_hist_m=height_hist,
        out_path=args.height_figure,
        height_min=z_min,
        height_max=z_max,
        figure_dpi=fig_dpi,
        seed_bbox=seed_bbox,
        source_lat=source_lat,
        source_lon=source_lon,
    )

    plot_trajectories_by_age(
        xlat=xlat,
        xlon=xlon,
        trajectory_i=trajectories["i"],
        trajectory_j=trajectories["j"],
        trajectory_active=trajectories["active"],
        trajectory_times_sec=trajectories["times"],
        out_path=args.age_figure,
        figure_dpi=fig_dpi,
        seed_bbox=seed_bbox,
        source_lat=source_lat,
        source_lon=source_lon,
    )

    if args.seeds_vertical_figure is not None:
        initial_parcels = state.get("initial_parcels")
        if initial_parcels is None:
            raise ValueError("Pickle does not contain initial parcels.")
        plot_seed_vertical_distribution(
            parcels=initial_parcels,
            out_path=args.seeds_vertical_figure,
            z_min=z_min,
            z_max=z_max,
            figure_dpi=fig_dpi,
            x_coords=initial_parcels.get("i"),
        )


if __name__ == "__main__":
    main()
