import argparse
import pickle
import numpy as np

from .plume_wrf import (
    plot_trajectories_by_height,
    plot_trajectories_by_age,
    plot_deposited_parcels_by_hour,
    plot_hourly_parcel_snapshots,
    plot_seed_vertical_distribution,
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Re-plot forward trajectories from a saved state pickle file."
    )
    parser.add_argument(
        "pickle_file",
        help="Path to the pickle file generated by plume_forwtraj.py.",
    )
    parser.add_argument(
        "--initial-height-figure",
        default="plume_initial_height_colored_replot.png",
        help="Output PNG for trajectories colored by initial height.",
    )
    parser.add_argument(
        "--age-figure",
        default="plume_age_colored_replot.png",
        help="Output PNG for trajectories colored by age.",
    )
    parser.add_argument(
        "--deposition-figure",
        default=None,
        help=(
            "Optional output PNG for deposited parcels only, "
            "colored by deposition hour since release."
        ),
    )
    parser.add_argument(
        "--seeds-vertical-figure",
        default=None,
        help="Optional PNG for the initial vertical distribution of parcels.",
    )
    parser.add_argument(
        "--hourly-output-dir",
        default=None,
        help=(
            "If set, save parcel-location maps at each whole hour since release to "
            "this output directory."
        ),
    )
    parser.add_argument(
        "--map-extent",
        nargs=4,
        type=float,
        metavar=("WEST", "SOUTH", "EAST", "NORTH"),
        help="Optional map extent override (west/south/east/north bounds) for all plots.",
    )
    parser.add_argument(
        "--figure-dpi",
        type=int,
        default=None,
        help="Optional DPI override for all saved figures.",
    )
    return parser.parse_args()


def main(args=None):
    if args is None:
        args = parse_args()

    with open(args.pickle_file, "rb") as fh:
        state = pickle.load(fh)

    grid = state["grid"]
    trajectories = state["trajectories"]
    script_args = state.get("args", {})

    xlat = np.asarray(grid["xlat"])
    xlon = np.asarray(grid["xlon"])

    height_hist = trajectories.get("height_hist_m")
    if height_hist is None:
        raise ValueError("Pickle does not contain height history.")

    seed_bbox = script_args.get("seed_bbox")
    if seed_bbox is not None:
        seed_bbox = tuple(seed_bbox)

    if args.figure_dpi is not None:
        fig_dpi = max(50, int(args.figure_dpi))
    else:
        fig_dpi = max(50, int(script_args.get("figure_dpi", 200)))
    z_min = script_args.get("z_min")
    z_max = script_args.get("z_max")
    source_lat = script_args.get("source_lat")
    source_lon = script_args.get("source_lon")
    if args.map_extent is not None:
        map_extent = tuple(args.map_extent)
    else:
        map_extent = script_args.get("map_extent")
        if map_extent is not None:
            map_extent = tuple(map_extent)

    if args.hourly_output_dir:
        traj_times_utc = None
        start_time_utc = state.get("metadata", {}).get("start_time")
        if start_time_utc is not None:
            try:
                t0 = np.datetime64(start_time_utc).astype("datetime64[s]")
                traj_seconds = np.rint(np.asarray(trajectories["times"], dtype=float)).astype(
                    np.int64
                )
                traj_times_utc = t0 + traj_seconds.astype("timedelta64[s]")
            except Exception:
                traj_times_utc = None

        n_hourly = plot_hourly_parcel_snapshots(
            xlat=xlat,
            xlon=xlon,
            trajectory_i=trajectories["i"],
            trajectory_j=trajectories["j"],
            trajectory_active=trajectories["active"],
            trajectory_k=trajectories.get("k"),
            trajectory_times_sec=trajectories["times"],
            out_dir=args.hourly_output_dir,
            height_hist_m=height_hist,
            figure_dpi=fig_dpi,
            seed_bbox=seed_bbox,
            source_lat=source_lat,
            source_lon=source_lon,
            map_extent=map_extent,
            trajectory_times_utc=traj_times_utc,
            tail_enabled=True,
            tail_steps=6,
        )
        print(
            "[diag] Hourly snapshots saved: "
            f"{n_hourly} file(s) in '{args.hourly_output_dir}' "
            "using 'parcel_positions_hour.XXXX.png' naming."
        )

    plot_trajectories_by_height(
        xlat=xlat,
        xlon=xlon,
        trajectory_i=trajectories["i"],
        trajectory_j=trajectories["j"],
        trajectory_active=trajectories["active"],
        trajectory_k=trajectories.get("k"),
        height_hist_m=height_hist,
        initial_heights_m=state.get("initial_parcels", {}).get("z_init"),
        out_path=args.initial_height_figure,
        height_min=None,
        height_max=None,
        figure_dpi=fig_dpi,
        seed_bbox=seed_bbox,
        source_lat=source_lat,
        source_lon=source_lon,
        map_extent=map_extent,
    )

    plot_trajectories_by_age(
        xlat=xlat,
        xlon=xlon,
        trajectory_i=trajectories["i"],
        trajectory_j=trajectories["j"],
        trajectory_active=trajectories["active"],
        trajectory_k=trajectories.get("k"),
        trajectory_times_sec=trajectories["times"],
        out_path=args.age_figure,
        figure_dpi=fig_dpi,
        seed_bbox=seed_bbox,
        source_lat=source_lat,
        source_lon=source_lon,
        map_extent=map_extent,
    )

    if args.deposition_figure is not None:
        plot_deposited_parcels_by_hour(
            xlat=xlat,
            xlon=xlon,
            trajectory_i=trajectories["i"],
            trajectory_j=trajectories["j"],
            trajectory_active=trajectories["active"],
            trajectory_k=trajectories.get("k"),
            trajectory_times_sec=trajectories["times"],
            out_path=args.deposition_figure,
            figure_dpi=fig_dpi,
            seed_bbox=seed_bbox,
            source_lat=source_lat,
            source_lon=source_lon,
            map_extent=map_extent,
        )

    if args.seeds_vertical_figure is not None:
        initial_parcels = state.get("initial_parcels")
        if initial_parcels is None:
            raise ValueError("Pickle does not contain initial parcels.")
        plot_seed_vertical_distribution(
            parcels=initial_parcels,
            out_path=args.seeds_vertical_figure,
            z_min=z_min,
            z_max=z_max,
            figure_dpi=fig_dpi,
            x_coords=initial_parcels.get("i"),
        )


if __name__ == "__main__":
    main()
